AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'bin/**'

# Customize rules
Metrics/LineLength:
  Max: 95

MethodLength:
  Max: 35

Metrics/AbcSize:
   Enabled: false

BlockLength:
  Max: 70
